"""Generate digit-only, run-length encoded 1-bit masks; no fonts enter the PBW."""
from pathlib import Path
from io import BytesIO
import hashlib
import json
import struct
from fontTools.ttLib import TTFont
from fontTools import subset
from fontTools.varLib.instancer import instantiateVariableFont
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
STATES, HEIGHT = 16, 80
SOURCES = [('western', 'RobotoFlex', '0123456789'),
           ('eastern', 'NotoSansArabic', '٠١٢٣٤٥٦٧٨٩'),
           ('devanagari', 'NotoSansDevanagari', '०१२३४५६७८९')]

def encode(image):
    """Lossless monochrome RLE: width,height; repeated rows,count,(x,length)*.

    Repeated scanlines collapse into rectangles, so runtime only fills rectangles.
    Offsets are little-endian uint32; records never require full-screen buffers.
    """
    w, h = image.size
    rows = []
    for y in range(h):
        runs, x = [], 0
        while x < w:
            if image.getpixel((x, y)):
                start = x
                while x < w and image.getpixel((x, y)):
                    x += 1
                runs.extend((start, x - start))
            else:
                x += 1
        rows.append(bytes([len(runs) // 2] + runs))
    data = bytearray([w, h])
    y = 0
    while y < h:
        end = y + 1
        while end < h and rows[end] == rows[y]:
            end += 1
        data.extend(bytes([end - y]) + rows[y])
        y = end
    return data

def main():
    out = ROOT / 'resources/numerals'
    out.mkdir(parents=True, exist_ok=True)
    maximum, report = 0, {}
    for name, source, digits in SOURCES:
        path = ROOT / f'tools/fonts/{source}.ttf'
        font = TTFont(path)
        assert all(ord(c) in font.getBestCmap() for c in digits), source
        sub = subset.Subsetter()
        sub.populate(text=digits)
        sub.subset(font)
        records = [None] * (10 * STATES)
        sheet = Image.new('L', (16 * 140, 10 * 106), 32)
        axes = {a.axisTag: a for a in font['fvar'].axes}
        for state in range(STATES):
            t = state / (STATES - 1)
            # Real variable outlines first; lighter wide masters temper stretched stems.
            location = {a: axis.defaultValue for a, axis in axes.items()}
            location['wdth'] = axes['wdth'].minValue + t * (axes['wdth'].maxValue - axes['wdth'].minValue)
            location['wght'] = 600 - 50 * t
            if 'opsz' in axes:
                location['opsz'] = 144
            instance = instantiateVariableFont(font, location, inplace=False)
            buffer = BytesIO()
            instance.save(buffer)
            raster_font = ImageFont.truetype(BytesIO(buffer.getvalue()), 384)
            width = round(18 + t * 90)
            for digit, char in enumerate(digits):
                box = raster_font.getbbox(char)
                im = Image.new('L', (box[2] - box[0], box[3] - box[1]))
                ImageDraw.Draw(im).text((-box[0], -box[1]), char, font=raster_font, fill=255)
                im = im.crop(im.getbbox())
                # Nonuniform horizontal deformation extends far beyond the wdth axis.
                # Supersampling keeps counters open; lighter narrow masters avoid closed counters.
                im = im.resize((width * 3, HEIGHT * 3), Image.Resampling.LANCZOS)
                im = im.resize((width, HEIGHT), Image.Resampling.LANCZOS).point(lambda p: 255 if p >= 128 else 0)
                # Arabic zero is a dot: retain that identity instead of a full-height bar.
                if name == 'eastern' and digit == 0:
                    dot = im.resize((max(5, width // 3), 14))
                    im = Image.new('L', (width, HEIGHT))
                    im.paste(dot, ((width - dot.width) // 2, (HEIGHT - 14) // 2))
                data = encode(im)
                maximum = max(maximum, len(data))
                records[digit * STATES + state] = data
                sheet.paste(im, (state * 140 + (140-width)//2, digit * 106 + 5))
        offset = (len(records) + 1) * 4
        offsets = [offset]
        for record in records:
            offset += len(record)
            offsets.append(offset)
        blob = struct.pack('<' + 'I' * len(offsets), *offsets) + b''.join(records)
        (out / f'{name}.bin').write_bytes(blob)
        preview = ROOT / 'build/previews'
        preview.mkdir(parents=True, exist_ok=True)
        sheet.save(preview / f'{name}.png')
        report[name] = {'bytes': len(blob), 'source': source, 'sha256': hashlib.sha256(path.read_bytes()).hexdigest()}
    (ROOT / 'src/c/numeral_assets.h').write_text(
        '// Generated by tools/generate_numerals.py\n#pragma once\n'
        f'#define NUMERAL_STATES {STATES}\n#define MASK_CAPACITY {maximum}\n')
    (out / 'manifest.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(report, indent=2), 'Maximum mask bytes:', maximum)

if __name__ == '__main__':
    main()
